/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SafePaySplitterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "emergencyWithdraw"
      | "feeBasisPoints"
      | "feeWallet"
      | "getStats"
      | "isOrderProcessed"
      | "owner"
      | "processPayment"
      | "processedOrders"
      | "renounceOwnership"
      | "setFeeBasisPoints"
      | "setFeeWallet"
      | "setSupportedToken"
      | "supportedTokens"
      | "totalFeeCollected"
      | "totalProcessed"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeeBasisPointsUpdated"
      | "FeeWalletUpdated"
      | "OwnershipTransferred"
      | "PaymentProcessed"
      | "TokenSupportUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "feeBasisPoints",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "feeWallet", values?: undefined): string;
  encodeFunctionData(functionFragment: "getStats", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isOrderProcessed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processPayment",
    values: [AddressLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "processedOrders",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeBasisPoints",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSupportedToken",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "supportedTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalFeeCollected",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalProcessed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeBasisPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feeWallet", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getStats", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isOrderProcessed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processedOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeBasisPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSupportedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalFeeCollected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalProcessed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace FeeBasisPointsUpdatedEvent {
  export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
  export type OutputTuple = [oldFee: bigint, newFee: bigint];
  export interface OutputObject {
    oldFee: bigint;
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeWalletUpdatedEvent {
  export type InputTuple = [oldWallet: AddressLike, newWallet: AddressLike];
  export type OutputTuple = [oldWallet: string, newWallet: string];
  export interface OutputObject {
    oldWallet: string;
    newWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentProcessedEvent {
  export type InputTuple = [
    merchant: AddressLike,
    token: AddressLike,
    orderId: BytesLike,
    grossAmount: BigNumberish,
    merchantAmount: BigNumberish,
    feeAmount: BigNumberish
  ];
  export type OutputTuple = [
    merchant: string,
    token: string,
    orderId: string,
    grossAmount: bigint,
    merchantAmount: bigint,
    feeAmount: bigint
  ];
  export interface OutputObject {
    merchant: string;
    token: string;
    orderId: string;
    grossAmount: bigint;
    merchantAmount: bigint;
    feeAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenSupportUpdatedEvent {
  export type InputTuple = [token: AddressLike, supported: boolean];
  export type OutputTuple = [token: string, supported: boolean];
  export interface OutputObject {
    token: string;
    supported: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SafePaySplitter extends BaseContract {
  connect(runner?: ContractRunner | null): SafePaySplitter;
  waitForDeployment(): Promise<this>;

  interface: SafePaySplitterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  emergencyWithdraw: TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  feeBasisPoints: TypedContractMethod<[], [bigint], "view">;

  feeWallet: TypedContractMethod<[], [string], "view">;

  getStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, string, bigint] & {
        _totalProcessed: bigint;
        _totalFeeCollected: bigint;
        _feeWallet: string;
        _feeBasisPoints: bigint;
      }
    ],
    "view"
  >;

  isOrderProcessed: TypedContractMethod<
    [orderId: BytesLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  processPayment: TypedContractMethod<
    [merchant: AddressLike, token: AddressLike, orderId: BytesLike],
    [void],
    "nonpayable"
  >;

  processedOrders: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setFeeBasisPoints: TypedContractMethod<
    [_feeBasisPoints: BigNumberish],
    [void],
    "nonpayable"
  >;

  setFeeWallet: TypedContractMethod<
    [_feeWallet: AddressLike],
    [void],
    "nonpayable"
  >;

  setSupportedToken: TypedContractMethod<
    [token: AddressLike, supported: boolean],
    [void],
    "nonpayable"
  >;

  supportedTokens: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  totalFeeCollected: TypedContractMethod<[], [bigint], "view">;

  totalProcessed: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "feeBasisPoints"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "feeWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, string, bigint] & {
        _totalProcessed: bigint;
        _totalFeeCollected: bigint;
        _feeWallet: string;
        _feeBasisPoints: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isOrderProcessed"
  ): TypedContractMethod<[orderId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "processPayment"
  ): TypedContractMethod<
    [merchant: AddressLike, token: AddressLike, orderId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "processedOrders"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeBasisPoints"
  ): TypedContractMethod<[_feeBasisPoints: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeWallet"
  ): TypedContractMethod<[_feeWallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSupportedToken"
  ): TypedContractMethod<
    [token: AddressLike, supported: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportedTokens"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalFeeCollected"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalProcessed"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "FeeBasisPointsUpdated"
  ): TypedContractEvent<
    FeeBasisPointsUpdatedEvent.InputTuple,
    FeeBasisPointsUpdatedEvent.OutputTuple,
    FeeBasisPointsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FeeWalletUpdated"
  ): TypedContractEvent<
    FeeWalletUpdatedEvent.InputTuple,
    FeeWalletUpdatedEvent.OutputTuple,
    FeeWalletUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PaymentProcessed"
  ): TypedContractEvent<
    PaymentProcessedEvent.InputTuple,
    PaymentProcessedEvent.OutputTuple,
    PaymentProcessedEvent.OutputObject
  >;
  getEvent(
    key: "TokenSupportUpdated"
  ): TypedContractEvent<
    TokenSupportUpdatedEvent.InputTuple,
    TokenSupportUpdatedEvent.OutputTuple,
    TokenSupportUpdatedEvent.OutputObject
  >;

  filters: {
    "FeeBasisPointsUpdated(uint256,uint256)": TypedContractEvent<
      FeeBasisPointsUpdatedEvent.InputTuple,
      FeeBasisPointsUpdatedEvent.OutputTuple,
      FeeBasisPointsUpdatedEvent.OutputObject
    >;
    FeeBasisPointsUpdated: TypedContractEvent<
      FeeBasisPointsUpdatedEvent.InputTuple,
      FeeBasisPointsUpdatedEvent.OutputTuple,
      FeeBasisPointsUpdatedEvent.OutputObject
    >;

    "FeeWalletUpdated(address,address)": TypedContractEvent<
      FeeWalletUpdatedEvent.InputTuple,
      FeeWalletUpdatedEvent.OutputTuple,
      FeeWalletUpdatedEvent.OutputObject
    >;
    FeeWalletUpdated: TypedContractEvent<
      FeeWalletUpdatedEvent.InputTuple,
      FeeWalletUpdatedEvent.OutputTuple,
      FeeWalletUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PaymentProcessed(address,address,bytes32,uint256,uint256,uint256)": TypedContractEvent<
      PaymentProcessedEvent.InputTuple,
      PaymentProcessedEvent.OutputTuple,
      PaymentProcessedEvent.OutputObject
    >;
    PaymentProcessed: TypedContractEvent<
      PaymentProcessedEvent.InputTuple,
      PaymentProcessedEvent.OutputTuple,
      PaymentProcessedEvent.OutputObject
    >;

    "TokenSupportUpdated(address,bool)": TypedContractEvent<
      TokenSupportUpdatedEvent.InputTuple,
      TokenSupportUpdatedEvent.OutputTuple,
      TokenSupportUpdatedEvent.OutputObject
    >;
    TokenSupportUpdated: TypedContractEvent<
      TokenSupportUpdatedEvent.InputTuple,
      TokenSupportUpdatedEvent.OutputTuple,
      TokenSupportUpdatedEvent.OutputObject
    >;
  };
}
