// Shared state for demo orders (in-memory, resets on cold start)

export interface DemoOrder {
  id: string;
  merchant_id: string;
  status: string;
  fiat_amount: number;
  fiat_currency: string;
  net_receive: number;
  settlement_currency: string;
  settlement_network: string;
  pay_currency?: string;
  pay_network?: string;
  deposit_address?: string;
  deposit_amount?: number;
  deposit_memo?: string;
  provider?: string;
  provider_swap_id?: string;
  deposit_tx_hash?: string;
  settlement_tx_hash?: string;
  settlement_amount?: number;
  success_url: string;
  cancel_url: string;
  expires_at: string;
  is_demo: boolean;
  created_at: string;
}

// In-memory storage for demo orders
export const demoOrders = new Map<string, DemoOrder>();

// Demo merchant configuration
export const DEMO_MERCHANT = {
  id: 'demo_merchant_001',
  store_name: 'Demo Store',
  settlement_currency: 'USDC',
  settlement_network: 'POLYGON',
  payout_address: '0x742d35Cc6634C0532925a3b844Bc454e4438f44E',
};

// Demo deposit addresses for different currencies
// NOTE: These are DEMO-ONLY addresses used for UI display in the landing page demo.
// In PRODUCTION, deposit addresses are generated by swap providers (Exolix/FixedFloat)
// for each transaction - we never control or hold customer funds.
export const DEMO_ADDRESSES: Record<string, string> = {
  // These use valid address formats but are clearly demo addresses
  BTC: 'bc1qDemo0000000000000000000000SafePay',
  ETH: '0xDem0000000000000000000000000SafePay01',
  SOL: 'Demo11111111111111111111111111SafePay',
  LTC: 'ltc1qDemo000000000000000000000SafePay',
  DOGE: 'DDemoSafePayAddress00000000000000',
  XRP: 'rDemoSafePayAddress000000000000',
  USDT: '0xDem0000000000000000000000000SafePay02',
  USDC: '0xDem0000000000000000000000000SafePay03',
  TRX: 'TDemoSafePayAddress00000000000',
  MATIC: '0xDem0000000000000000000000000SafePay04',
  ADA: 'addr1_demo_safepay_address_for_testing_only',
  DOT: '1DemoSafePayAddress0000000000000000000',
  AVAX: '0xDem0000000000000000000000000SafePay05',
  LINK: '0xDem0000000000000000000000000SafePay06',
  SHIB: '0xDem0000000000000000000000000SafePay07',
  DEFAULT: '0xDem0000000000000000000000000SafePay00',
};

// Estimate deposit amount based on rough crypto prices
export function estimateDepositAmount(currency: string, usdAmount: number): number {
  const prices: Record<string, number> = {
    BTC: 97000,
    ETH: 3100,
    SOL: 190,
    LTC: 100,
    DOGE: 0.32,
    XRP: 2.5,
    ADA: 0.95,
    DOT: 7,
    AVAX: 35,
    LINK: 22,
    MATIC: 0.5,
    TRX: 0.23,
    SHIB: 0.000022,
    USDT: 1,
    USDC: 1,
  };

  const price = prices[currency.toUpperCase()] || 100;
  return Number((usdAmount / price).toFixed(8));
}

// Generate random hex string
export function generateRandomHex(length: number): string {
  const chars = '0123456789abcdef';
  let result = '';
  for (let i = 0; i < length; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
}

// Cleanup old demo orders (older than 1 hour)
export function cleanupOldDemoOrders(): void {
  const oneHourAgo = Date.now() - 60 * 60 * 1000;
  for (const [id, order] of demoOrders.entries()) {
    if (new Date(order.created_at).getTime() < oneHourAgo) {
      demoOrders.delete(id);
    }
  }
}
